[package]

name = "differential-geometry"
version = "0.1.0"
authors = [ "Bartłomiej Kamiński <fizyk20@gmail.com>" ]
description = "A library for differential-geometric calculations"
license = "MIT"
repository = "https://github.com/fizyk20/differential-geometry.git"

[lib]

name = "diffgeom"
crate-type = ["rlib", "dylib"]

[dependencies]
typenum = "1.3"
generic-array = ">=0.2"
